---
AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Create a central S3 bucket for CloudFormation

Parameters:
  BucketName:
    Type: String
    Description: Enter S3 bucket name
    AllowedPattern: ^[-a-zA-Z0-9]$

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  CloudFormationBucket:
    Description: Central CloudFormation S3 bucket
    Value: !Ref Bucket
    Export:
      Name: CloudFormation-Bucket